src/__init__.py
import os
from flask import Flask


def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(SECRET_KEY="dev")

    os.makedirs(app.instance_path, exist_ok=True)

    from . import api, routes

    app.register_blueprint(api.bp)
    app.register_blueprint(routes.bp)

    return app

src/api/__init__.py
from flask import Blueprint

bp = Blueprint("api", __name__, url_prefix="/api")

from . import (
    authorizations,
    billing_agreements,
    captures,
    identity,
    orders,
    partner,
    vault,
    webhooks,
)

bp.register_blueprint(authorizations.bp)
bp.register_blueprint(billing_agreements.bp)
bp.register_blueprint(captures.bp)
bp.register_blueprint(identity.bp)
bp.register_blueprint(orders.bp)
bp.register_blueprint(partner.bp)
bp.register_blueprint(vault.bp)
bp.register_blueprint(webhooks.bp)

src/routes.py
from flask import Blueprint, current_app, render_template, request

bp = Blueprint("routes", __name__, url_prefix="/")


def get_partner_and_merchant_config(is_fastlane=False, is_direct_merchant=False):
    if is_fastlane:
        if is_direct_merchant:
            return {
                "partner_id": current_app.config["FASTLANE_MERCHANT_ID"],
                "partner_client_id": current_app.config["FASTLANE_MERCHANT_CLIENT_ID"],
                "partner_bn_code": current_app.config["FASTLANE_MERCHANT_BN_CODE"],
                "merchant_id": current_app.config["FASTLANE_MERCHANT_ID"],
            }
        else:
            return {
                "partner_id": current_app.config["FASTLANE_PARTNER_ID"],
                "partner_client_id": current_app.config["FASTLANE_PARTNER_CLIENT_ID"],
                "partner_bn_code": current_app.config["FASTLANE_PARTNER_BN_CODE"],
                "merchant_id": current_app.config["FASTLANE_MERCHANT_ID"],
            }
    else:
        return {
            "partner_id": current_app.config["PARTNER_ID"],
            "partner_client_id": current_app.config["PARTNER_CLIENT_ID"],
            "partner_bn_code": current_app.config["PARTNER_BN_CODE"],
            "merchant_id": current_app.config["MERCHANT_ID"],
        }


@bp.route("onboarding/")
def onboarding():
    """Return the rendered onboarding page from its template."""

    template = "onboarding.html"
    partner_config = get_partner_and_merchant_config()
    del partner_config["merchant_id"]

    return render_template(
        template,
        **partner_config,
        favicon=current_app.config["favicon"],
    )


@bp.route("")
@bp.route("checkout/", endpoint="checkout-canonical")
@bp.route("checkout/branded/")
def checkout_branded():
    """Return the rendered Branded checkout page from its template."""

    template = "checkout-branded.html"
    partner_and_merchant_config = get_partner_and_merchant_config()

    return render_template(
        template,
        method="branded",
        **partner_and_merchant_config,
        favicon=current_app.config["favicon"],
    )


@bp.route("checkout/google-pay/")
def checkout_google_pay():
    """Return the rendered Google Pay checkout page from its template."""

    template = "checkout-google-pay.html"
    partner_and_merchant_config = get_partner_and_merchant_config()

    return render_template(
        template,
        method="google-pay",
        **partner_and_merchant_config,
        favicon=current_app.config["favicon"],
    )


@bp.route("checkout/hosted-v1/")
def checkout_hosted_v1():
    """Return the rendered Hosted Fields v1 checkout page from its template."""

    template = "checkout-hf-v1.html"
    partner_and_merchant_config = get_partner_and_merchant_config()

    return render_template(
        template,
        method="hosted-v1",
        **partner_and_merchant_config,
        favicon=current_app.config["favicon"],
    )


@bp.route("checkout/hosted-v2/")
def checkout_hosted_v2():
    """Return the rendered Hosted Fields v2 checkout page from its template."""

    template = "checkout-hf-v2.html"
    partner_and_merchant_config = get_partner_and_merchant_config()

    return render_template(
        template,
        method="hosted-v2",
        **partner_and_merchant_config,
        favicon=current_app.config["favicon"],
    )


@bp.route("checkout/fastlane/")
def checkout_fastlane():
    """Return the rendered Fastlane checkout page from its template."""

    template = "checkout-fastlane.html"

    is_direct_merchant = request.args.get("PPCP") == "direct-merchant"
    partner_and_merchant_config = get_partner_and_merchant_config(
        is_fastlane=True, is_direct_merchant=is_direct_merchant
    )

    return render_template(
        template,
        method="fastlane",
        **partner_and_merchant_config,
        favicon=current_app.config["favicon"],
    )


@bp.route("statuses/")
def statuses():
    """Return the rendered statuses page from its template."""

    template = "statuses.html"
    partner_and_merchant_config = get_partner_and_merchant_config()

    return render_template(
        template,
        **partner_and_merchant_config,
        favicon=current_app.config["favicon"],
    )

src/templates/checkout-branded-donations.html
{% extends "base.html" %}

{% block controls %}
<a href="/" 
  id="a-details" 
  target="_blank"
  class="px-2 py-1 bg-blue-700 rounded-lg text-white hover:underline"
  style="display: none">
  Order details
</a>
{% endblock %}

{% block checkout %}
<!-- Empty (for now) button container -->
<div class="smart-button-container", id="smart-button-container">
  <div style="text-align: center;">
    <div id="paypal-button-container"></div>
  </div>
</div>

<!-- Import PayPal Javascript SDK with Partner's credentials -->
<script src="https://www.paypal.com/sdk/js?client-id={{ partner_client_id }}&merchant-id={{ payee_id }}&currency=USD&intent=capture&commit=true&enable-funding=venmo,paylater&debug=true" data-partner-attribution-id="{{ bn_code }}"></script>

<script>
  var orderId;
  function initPayPalButton() {
    paypal.Buttons({
      createOrder: function (data, actions) {
        console.log("Creating the order...")
        return fetch('/api/orders/create', {
          headers: {'Content-Type': 'application/json'},
          method: 'POST',
          body: JSON.stringify({
            price: "{{ product['price'] }}", 
            payee_id: "{{ payee_id }}",
            is_donation: true
          })
        }).then(function(res) {
          return res.json();
        }).then(function(data) {
          orderId = data.id;
          setOrderDetails();
          return orderId;
        })
      },
      onApprove: function(data, actions) {
        return fetch('/api/orders/capture/' + data.orderID, {
          method: 'POST',
        }).then(function(res) {
          return res.json();
        }).then(function(captureData) {
          // Your server response structure and key names are what you choose
          if (captureData.error === 'INSTRUMENT_DECLINED') {
            return actions.restart();
          }
        })
      },
    }).render('#paypal-button-container');
  }
  initPayPalButton();
  function setOrderDetails() {
    let aDetails = document.getElementById("a-details");
    aDetails.href = "http://localhost:5000/store/order-details/" + orderId;
    aDetails.style.display = "";
  }
</script>
{% endblock %}

src/templates/checkout-branded-ppgf.html
{% extends "base.html" %}

{% block controls %}
<a href="/" 
  id="a-details" 
  target="_blank"
  class="px-2 py-1 bg-blue-700 rounded-lg text-white hover:underline"
  style="display: none">
  Order details
</a>
{% endblock %}

{% block checkout %}
<!-- Empty (for now) button container -->
<div class="smart-button-container", id="smart-button-container">
  <div style="text-align: center;">
    <div id="paypal-button-container"></div>
  </div>
</div>

<!-- Import PayPal Javascript SDK with Partner's credentials -->
<script src="https://www.paypal.com/sdk/js?client-id={{ partner_client_id }}&merchant-id={{ payee_id }}&currency=USD&intent=capture&commit=true&enable-funding=venmo,paylater" data-partner-attribution-id="{{ bn_code }}"></script>

<script>
  var orderId;
  function initPayPalButton() {
    paypal.Buttons({
      createOrder: function (data, actions) {
        console.log("Creating the order...")
        return fetch('/api/orders/create-ppgf', {
          headers: {'Content-Type': 'application/json'},
          method: 'POST',
          body: JSON.stringify({
            price: "{{ product['price'] }}", 
            payee_id: "{{ payee_id }}",
          })
        }).then(function(res) {
          return res.json();
        }).then(function(data) {
          orderId = data.id;
          setOrderDetails();
          return orderId;
        })
      },
      onApprove: function(data, actions) {
        return fetch('/api/orders/capture/' + data.orderID, {
          method: 'POST',
        }).then(function(res) {
          return res.json();
        }).then(function(captureData) {
          // Your server response structure and key names are what you choose
          if (captureData.error === 'INSTRUMENT_DECLINED') {
            return actions.restart();
          }
        })
      },
    }).render('#paypal-button-container');
  }
  initPayPalButton();
  function setOrderDetails() {
    let aDetails = document.getElementById("a-details");
    aDetails.href = "http://localhost:5000/store/order-details/" + orderId;
    aDetails.style.display = "";
  }
</script>
{% endblock %}

src/templates/checkout-branded-sdk-only.html
{% extends "base.html" %}

{% block controls %}
<a href="/" 
  id="a-details" 
  target="_blank"
  class="px-2 py-1 bg-blue-700 rounded-lg text-white hover:underline"
  style="display: none">
  Order details
</a>
{% endblock %}

{% block checkout %}
<!-- Empty (for now) button container -->
<div class="smart-button-container", id="smart-button-container">
  <div style="text-align: center;">
    <div id="paypal-button-container"></div>
  </div>
</div>

<!-- Import PayPal Javascript SDK with Partner's credentials -->
<script src="https://www.paypal.com/sdk/js?client-id={{ partner_client_id }}&merchant-id={{ payee_id }}&currency=USD&intent=capture&commit=true&enable-funding=venmo,paylater" data-partner-attribution-id="{{ bn_code }}"></script>

<script>
  var orderId;
  function initPayPalButton() {
    paypal.Buttons({
      createOrder: function (data, actions) {
        return actions.order.create({
          intent: "CAPTURE",
          purchase_units: [{
            custom_id: "Up to 127 characters can go here!",
            payee: {merchant_id: "{{ payee_id }}"},
            amount: {
              currency_code: "USD",
              value: "{{ product['price'] }}",
            },
          }],
          application_context: {
            return_url: "http://localhost:5000/",
            cancel_url: "http://localhost:5000/",
            shipping_preference: "GET_FROM_FILE",
          },
        }).then(function (orderID) {
          orderId = orderID;
          setOrderDetails();
          return orderID;
        });
      },
      onApprove: function(data, actions) {
        return actions.order.capture()
      },
    }).render('#paypal-button-container');
  }
  initPayPalButton();
  function setOrderDetails() {
    let aDetails = document.getElementById("a-details");
    aDetails.href = "http://localhost:5000/store/order-details/" + orderId;
    aDetails.style.display = "";
  }
</script>
{% endblock %}

src/templates/checkout-branded.html
{% extends 'checkout.html' %}

{% block additional_sdk_options %}
<div>
  <label for="button-label">
    Button label
  </label>
  <select name="button-label" id="button-label">
    <option value="paypal" selected>PayPal</option>
    <option value="checkout">Checkout</option>
    <option value="buynow">Buy Now</option>
    <option value="pay">Pay with</option>
    <option value="donate">Donate</option>
  </select>
</div>
{% endblock additional_sdk_options %}

{% block checkout_div %}
<script type="module">
  import {
    loadOptions,
    setOptions
  } from "{{ url_for('static', filename='utils.js') }}";
  import {
    setupEventListeners,
    buildScriptElement
  } from "{{ url_for('static', filename='checkout.js') }}";
  import loadButtons from "{{ url_for('static', filename='checkout-branded.js') }}";
  import buyerNotPresentCheckout from "{{ url_for('static', filename='checkout-buyer-not-present.js') }}";
  window.addEventListener('load', async function() {
    const options = loadOptions()
    window.sessionStorage.clear()
    setOptions(options)

    buildScriptElement(loadButtons, 'branded')
    setupEventListeners(() => {
      buildScriptElement(loadButtons, 'branded')
    })

    document.getElementById('buyer-not-present-checkout').addEventListener('click', buyerNotPresentCheckout)
  })
</script>
<div id="checkout-branded">
  <div id="paypal-button-container"></div>
</div>
{% endblock checkout_div %}

src/templates/checkout-google-pay.html
{% extends 'checkout.html' %}

{% block other_options %}
<fieldset id="google-pay-options">
  <details open>
    <summary>
      <span>
        <legend>
          Google Pay Button options
        </legend>
      </span>
    </summary>
    <div>
      <label for="google-pay-button-color">
        Color
      </label>
      <select name="google-pay-button-color" id="google-pay-button-color">
        <option selected>Default</option>
        <option>Black</option>
        <option>White</option>
      </select>
    </div>
    <div>
      <label for="google-pay-button-type">
        Label
      </label>
      <select id="google-pay-button-type" name="google-pay-button-type">
        <option>Book</option>
        <option>Buy</option>
        <option>Checkout</option>
        <option>Donate</option>
        <option>Order</option>
        <option>Pay</option>
        <option selected>Plain</option>
        <option>Subscribe</option>
      </select>
    </div>
    <div>
      <label for="google-pay-button-locale">
        Language
      </label>
      <select id="google-pay-button-locale" name="google-pay-button-locale">
        <option value="ar">Arabic</option>
        <option value="bg">Bulgarian</option>
        <option value="ca">Catalan</option>
        <option value="zh">Chinese</option>
        <option value="hr">Croatian</option>
        <option value="cs">Czech</option>
        <option value="da">Danish</option>
        <option value="nl">Dutch</option>
        <option value="en" selected>English</option>
        <option value="et">Estonian</option>
        <option value="fi">Finnish</option>
        <option value="fr">French</option>
        <option value="de">German</option>
        <option value="el">Greek</option>
        <option value="id">Indonesian</option>
        <option value="it">Italian</option>
        <option value="ja">Japanese</option>
        <option value="ko">Korean</option>
        <option value="ms">Malay</option>
        <option value="no">Norwegian</option>
        <option value="pl">Polish</option>
        <option value="pt">Portuguese</option>
        <option value="ru">Russian</option>
        <option value="sr">Serbian</option>
        <option value="sk">Slovak</option>
        <option value="sl">Slovenian</option>
        <option value="es">Spanish</option>
        <option value="sv">Swedish</option>
        <option value="th">Thai</option>
        <option value="tr">Turkish</option>
        <option value="uk">Ukrainian</option>
      </select>
    </div>
  </details>
</fieldset>
{{ super() }}
{% endblock other_options %}

{% block vault_options %}
{% endblock vault_options %}


{% block checkout_div %}
<script async src="https://pay.google.com/gp/p/js/pay.js"></script>
<script type="module">
  import {
    loadOptions,
    saveOptionsAndReloadPage,
    setOptions
  } from "{{ url_for('static', filename='utils.js') }}";
  import {
    setupEventListeners,
    buildScriptElement
  } from "{{ url_for('static', filename='checkout.js') }}";
  import loadGooglePay from "{{ url_for('static', filename='checkout-google-pay.js') }}";

  window.addEventListener('load', function() {
    const options = loadOptions()
    window.sessionStorage.clear()
    setOptions(options)

    buildScriptElement(loadGooglePay, 'google-pay')
    setupEventListeners(saveOptionsAndReloadPage)
  })
</script>
<div id="checkout-google-pay">
</div>
{% endblock checkout_div %}

src/templates/checkout-hf-v1.html
{% extends 'checkout.html' %}

{% block other_options %}
<fieldset id="hosted-v1-options">
  <details open>
    <summary>
      <span>
        <legend>
          Hosted Fields v1 options
        </legend>
      </span>
    </summary>
    <div>
      <label for="3ds-preference">
        3D-Secure (3DS)
      </label>
      <select name="3ds-preference" id="3ds-preference">
        <option value="" selected>None</option>
        <option value="SCA_WHEN_REQUIRED">When required</option>
        <option value="SCA_ALWAYS">Always</option>
      </select>
    </div>
  </details>
</fieldset>
{{ super() }}
{% endblock other_options %}

{% block vault_options %}
{% endblock vault_options %}

{% block checkout_div %}
<script type="module">
  import {
    setOptions,
    getOptions,
    loadOptions,
    saveOptionsAndReloadPage
  } from "{{ url_for('static', filename='utils.js') }}";
  import {
    setupEventListeners,
    buildScriptElement
  } from "{{ url_for('static', filename='checkout.js') }}";
  import loadHostedFields from "{{ url_for('static', filename='checkout-hf-v1.js') }}";
  window.addEventListener('load', async function () {
    const options = loadOptions()
    window.sessionStorage.clear()
    setOptions(options)

    buildScriptElement(loadHostedFields, 'hosted-fields-v1')
    setupEventListeners(saveOptionsAndReloadPage)
  })
</script>
<div>
  <form id="hf-v1-form">
    <label for="card-number">Card Number</label>
    <div id="card-number"></div>

    <label for="expiration-date">Expiration Date</label>
    <div id="expiration-date"></div>

    <label for="cvv">CVV</label>
    <div id="cvv"></div>

    <label for="cardholder-name">Name on Card</label>
    <input type="text" form="options-form" id="cardholder-name" name="cardholder-name" placeholder="Card holder name">
    <label>Billing Address</label>
    <input type="text" form="options-form" id="billing-address-line-1" name="billing-address-line-1" placeholder="Street address">
    <input type="text" form="options-form" id="billing-address-line-2" name="billing-address-line-2" placeholder="Unit">
    <input type="text" form="options-form" id="billing-address-admin-area-1" name="billing-address-admin-area-1" placeholder="City">
    <input type="text" form="options-form" id="billing-address-admin-area-2" name="billing-address-admin-area-2" placeholder="State">
    <input type="text" form="options-form" id="billing-address-postal-code" name="billing-address-postal-code" placeholder="Postal code">
    <input type="text" form="options-form" id="billing-address-country-code" name="billing-address-country-code" placeholder="Country code">

    <button value="submit" id="pay-button">Pay</button>
  </form>
</div>
{% endblock checkout_div %}

src/templates/checkout.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<script type="module">
  import { changeCheckout } from "{{ url_for('static', filename='checkout.js') }}";
  window.addEventListener('load', () => {
    const checkoutMethod = document.getElementById('checkout-method')
    checkoutMethod.addEventListener('change', changeCheckout)
  })

</script>
{% endblock head %}


{% block preamble_options %}
<fieldset id="fieldset-preamble-options">
  {% block inner_preamble_options %}
  <div>
    <label for="checkout-method">
      Checkout Method
    </label>
    <select name='checkout-method' id='checkout-method'>
      <optgroup label="Buttons">
        <option
          value="{{ url_for('routes.checkout_branded') }}"
          {{ 'selected' if method == 'branded' else '' }}
        >Branded</option>
        <option
          value="{{ url_for('routes.checkout_google_pay') }}"
          {{ 'selected' if method == 'google-pay' else '' }}
        >Google Pay</option>
      </optgroup>
      <optgroup label="ACDC">
        <option
          value="{{ url_for('routes.checkout_fastlane') }}"
          {{ 'selected' if method == 'fastlane' else '' }}
        >Fastlane</option>
        <option
          value="{{ url_for('routes.checkout_hosted_v2') }}"
          {{ 'selected' if method == 'hosted-v2' else '' }}
        >Hosted Fields v2</option>
        <option
          value="{{ url_for('routes.checkout_hosted_v1') }}"
          {{ 'selected' if method == 'hosted-v1' else '' }}
        >Hosted Fields v1</option>
      </optgroup>
    </select>
  </div>
  {% endblock inner_preamble_options %}
</fieldset>
{% endblock preamble_options %}


{% block other_options %}
<fieldset id="paypal-sdk-options">
  <details open>
    <summary>
      <span>
        <legend>
          PayPal JS SDK options
        </legend>
      </span>
    </summary>
    <div>
      <label for="buyer-country-code">
        Buyer country
      </label>
      <select name="buyer-country-code" id="buyer-country-code">
        {% include 'country-options.html' %}
      </select>
    </div>
    <div>
      <label for="currency-code">
        Currency
      </label>
      <select name="currency-code" id="currency-code">
        <option value="AUD">Australian dollar</option>
        <option value="BRL">Brazilian real</option>
        <option value="CAD">Canadian dollar</option>
        <option value="CNY">Chinese Renmenbi</option>
        <option value="CZK">Czech koruna</option>
        <option value="DKK">Danish krone</option>
        <option value="EUR">Euro</option>
        <option value="HKD">Hong Kong dollar</option>
        <option value="ILS">Israeli new shekel</option>
        <option value="MYR">Malaysian ringgit</option>
        <option value="MXN">Mexican peso</option>
        <option value="NZD">New Zealand dollar</option>
        <option value="NOK">Norwegian krone</option>
        <option value="PHP">Philippine peso</option>
        <option value="PLN">Polish złoty</option>
        <option value="GBP">Pound sterling</option>
        <option value="RUB">Russian ruble</option>
        <option value="SGD">Singapore dollar</option>
        <option value="SEK">Swedish krona</option>
        <option value="CHF">Swiss franc</option>
        <option value="THB">Thai baht</option>
        <option value="USD" selected>United States dollar</option>
      </select>
    </div>
    <div>
      <label for="intent">
        Intent
      </label>
      <select name="intent" id="intent">
        <option value="CAPTURE" selected>Capture</option>
        <option value="AUTHORIZE">Authorize</option>
      </select>
    </div>
    {% block additional_sdk_options %}
    {% endblock additional_sdk_options %}
  </details>
</fieldset>
{% block vault_options %}
<fieldset id="vault-options">
  <details open>
    <summary>
      <span>
        <legend>
          Vault v3 options
        </legend>
      </span>
    </summary>
    <div>
      <label for="vault-flow">
        Flow
      </label>
      <select name="vault-flow" id="vault-flow">
        <option value="" selected>None</option>
        <option value="first-time-buyer">First-time buyer</option>
        <option value="return-buyer">Return buyer</option>
        <option value="buyer-not-present">Buyer not present</option>
      </select>
    </div>
    <div class="first-time-buyer return-buyer buyer-not-present">
      <label for="vault-level">
        Vault level
      </label>
      <select name="vault-level" id="vault-level">
        <option value="PLATFORM" selected>Partner-level</option>
        <option value="MERCHANT">Merchant-level</option>
      </select>
    </div>
    <div class="return-buyer">
      <label for="customer-id">
        Customer ID
      </label>
      <input name="customer-id" id="customer-id">
    </div>
    <div class="first-time-buyer">
      <label for="merchant-customer-id">
        Merchant Customer ID
      </label>
      <input name="merchant-customer-id" id="merchant-customer-id"/>
    </div>
    <div class="first-time-buyer">
      <label for="permit-multiple-payment-tokens">
        Permit multiple tokens
      </label>
      <select name="permit-multiple-payment-tokens" id="permit-multiple-payment-tokens">
        <option value="true" selected>True</option>
        <option value="">False</option>
      </select>
    </div>
    <div class="first-time-buyer">
      <label for="vault-without-purchase">
        Vault without purchase
      </label>
      <input type="checkbox" name="vault-without-purchase" id="vault-without-purchase">
    </div>
    <div class="buyer-not-present">
      <label for="vault-id">
        Vault ID
      </label>
      <input name="vault-id" id="vault-id">
    </div>
    <div class="buyer-not-present">
      <label for="vault-payment-source">
        Payment source
      </label>
      <div>
        <select name="vault-payment-source" id="vault-payment-source">
          <option value="paypal" selected>PayPal</option>
          <option value="card">Card</option>
        </select>
        <button type="button" data-method="post" id="buyer-not-present-checkout">Pay</button>
      </div>
    </div>
  </details>
</fieldset>
{% endblock vault_options %}
{% include 'checkout-options.html' %}
{% endblock other_options %}

{% block right_col %}
<the-tabs>
  <div role='tablist'>
    <button role='tab' aria-selected='true'>Checkout</button>
    <button role='tab' id="tab-api-calls">API Calls</button>

    <button type="button" id="download-all" data-method class="postman">Download all for Postman</button>
  </div>
  <div role='tabpanel' data-page="checkout">
    <script id="paypal-js-sdk"></script>
    {% block checkout_div %}
    {% endblock checkout_div %}
  </div>
  <div role='tabpanel' hidden>
    <the-tabs>
      <div role='tablist'>
      </div>
    </the-tabs>
  </div>
</the-tabs>
{% endblock right_col %}

src/templates/sign_up.html
<div dir="ltr" style="text-align: left;" trbidi="on">
  <script>
    (function(d, s, id) {
      var js, ref = d.getElementsByTagName(s)[0];
      if (!d.getElementById(id)) {
        js = d.createElement(s);
        js.id = id;
        js.async = true;
        js.src = "https://www.paypal.com/webapps/merchantboarding/js/lib/lightbox/partner.js";
        ref.parentNode.insertBefore(js, ref);
      }
    }(document, "script", "paypal-js"));
  </script>
  <a data-paypal-button="true" href="{{ sign_up_link }}&displayMode=minibrowser" target="PPFrame">Sign up for PayPal</a>
</div>

<br/>

<a href={{ tracking_url }}>Status page</a>

src/templates/two-column-base.html
<!doctype html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script src="https://cdn.tailwindcss.com"></script>
		{% block head %}
		{% endblock %}
	</head>
	<body class="bg-slate-100 dark:bg-slate-900">
		<div class="max-w-7xl mx-auto">
			<div class="grid grid-cols-4 gap-2">
				<div class="col-span-1 h-screen bg-slate-50 ring-1 ring-slate-900/5 dark:bg-slate-800">
					<div id="left-col" class="mt-2 mx-2"> 
                        {% block left_col %}
						{% endblock %}
					</div>
				</div>
				<div class="col-span-3 h-screen bg-slate-50 ring-1 ring-slate-900/5 dark:bg-slate-800">
					<div id="right-col" class="mt-2 mx-2"> 
						{% block right_col %}
						{% endblock %}
					</div>
				</div>
			</div>
		</div>
	</body>
</html>